# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQAdOYm9azt6vLZFZnqF_CsSSEQ_Zkkr
"""

H1=["Alma",18,"15","computer"]
H2=["Narges",17,"16","computer"]
H3=["Hosna",18,"16","computer"]
H4=["Hedieh",20,"15","Graphic"]
H5=["Yasaman",15,"16","computer"]
H6=["Mahsa",19,"16","computer"]
HONAR=[H1,H2,H3,H4,H5]
HONAR.append(H6)
HONAR.remove(H3)
HONAR.insert(0,H4)
print(HONAR)

M=[18,19,13,20,16,14]
M.sort()
print(M)
M.reverse()
print(M)
m_copy=M.copy()
M.clear()